### ISSUE TITLE
Devanagari umlauts are so high that they are unseen

### ISSUE THREAD

**Issue by Mercury13** [notofonts/devanagari#11]
### Title 
Devanagari umlauts are really high

### Font 
NotoSerifDevanagari-Regular.ttf

### Where the font came from, and when
Site: this repo
Date: 2021-10-06

### Font Version
2.001

### OS name and version
W10 2020H2, but probably all OS

### Application name and version
LibreOffice.org 7.1, Qt 6.2, but probably all apps

### Issue
  1. Write any Devanagari letter + any Devanagari umlaut (I used 1CD1).
  2. Umlaut is almost unseen
  3. Umlaut should be seen
  4. In older Noto 1.01 OK. I compared pixel-to-pixel old and new, and new one’s letters are shifted a bit up.

### Character data
1CD0 Vedic tone Karshana
1CD1 Vedic tone Shara
1CD2 Vedic tone Prenkha
1CF4 Vedic tone Candra above
A8E0 Combining Devanagari digit Zero
…
A8F1 Combining Devanagari sign Avagraha

### Screenshot
2.001
![image](https://user-images.githubusercontent.com/10164882/136207285-90adaf2e-3659-4179-984a-3a4a508bef36.png)

1.01
![image](https://user-images.githubusercontent.com/10164882/136207669-cee54f5d-4d15-41a8-8a1c-38c890e46b6a.png)

**Comment by simoncozens** [comment]
The vedic accents in Noto Serif Devanagari have been in this position since we first got the sources 3 years ago. I'm not sure where you got 1.01 from, and I'm equally not sure that this is a problem - these very high marks are very high by design (see https://github.com/notofonts/devanagari/issues/27).
